### ISSUE TITLE
TypeError: moesif_middleware() takes exactly 1 argument (0 given)

### ISSUE THREAD

**Issue by mpetyx** [Moesif/moesifdjango#1]
Hello, I get the following error.
Any ideas?
I am using python 2.7.11 and django 1.11

Thank you in advance,
Michael.

```  
File "/Users/apilama/Desktop/projects/repos/orfium-django/orfium_project/wsgi.py", line 27, in <module>
    application = get_wsgi_application()
  File "/Users/apilama/Desktop/projects/venvs/orfium/venv/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/Users/apilama/Desktop/projects/venvs/orfium/venv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/Users/apilama/Desktop/projects/venvs/orfium/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 58, in load_middleware
    mw_instance = mw_class()
TypeError: moesif_middleware() takes exactly 1 argument (0 given)
```

**Comment by dgilling** [comment]
@mpetyx, sorry about the issues. We are taking a look and should have an update within the next 24 hrs.

**Comment by dgilling** [comment]
@mpetyx Do you have a snippet of code of how you initialize moesifdjango in your code and set the APPLICATION_ID and any options set? (The APPLICATION_ID is a write only key but recommended to still mask it out on GitHub Issues)

**Comment by dgilling** [comment]
@mpetyx That specific error occurs when Django 1.10 middleware is used with Django 1.9 or earlier. When using 1.9 or earlier, MoesifMiddlewarePre19 needs to be used (See [https://docs.djangoproject.com/en/1.11/topics/http/middleware/](https://docs.djangoproject.com/en/1.11/topics/http/middleware/)

You mentioned you're using 1.11, but can you double check the version 

`python2 -c "import django; print(django.get_version())"`

Also, can you try with the Django 1.9 or older version of the Moesif middleware and see what happens?
To use the Django 1.9 or older version version of middleware do the following instead:

```
MIDDLEWARE_CLASSES = [
    ...
    'moesifdjango.middleware_pre19.MoesifMiddlewarePre19',
    ...
    # other middlewares
]
```

Also, we will take an action to add more user friendly error printing.
